### ISSUE TITLE
Support AppSync as resource in CloudCatalog

### ISSUE THREAD

**Issue by debae** [boyney123/cloudcatalog#34]
### Description

It would be great to also support AppSync as a resource in CloudCatalog. At this moment it is imported as a generic resource, however it would be nice if we could also display some properties such as API type, the GraphQL endpoint, authentication mechanism.

**Comment by ibrahimcesar** [comment]
Hello,

I'll work on add AppSync to the project

**Comment by debae** [comment]
> Hello,
> 
> I'll work on add AppSync to the project

Already created a PR for this https://github.com/boyney123/cloudcatalog/pull/35 , @boyney123 you can assign this ticket to me.

**Comment by boyney123** [comment]
Thanks for the pull request, just merged it in! Congrats!
