### ISSUE TITLE
How to I embed simple images in my markdown?

### ISSUE THREAD

**Issue by matthelliwell2** [boyney123/cloudcatalog#40]
I've got a png file that I want to embed in one of my resource pages. Is there anyway to do this?

eg I have the lambda file resources/lambda/MyLambda.md. I also have the file MyLambda.png. Is there anyway to get the png to appear in the MyLambda page?

I've tried various combinations of markdown, such as ![Alt text](./MyLambda.png "My Diagram"), without any success.

**Comment by RobertoChiosa** [comment]
I run into similar issue and solved as follows:

1. Put the image `MyLambda.png` within the `.public` folder at the root of your project
2. Then you can reference the image within your `resources/lambda/MyLambda.md` file like this `![](/MyLambda.png)`
3. Now you should see your image when running the catalog

**Comment by boyney123** [comment]
Yeah that should do the trick! Did this work for you @matthelliwell2 ? Thanks for the reply @RobertoChiosa

**Comment by matthelliwell2** [comment]
I tried that yesterday and got it to work in time for my demo, so thanks for that.
